Reland [NFC] Move DroppedVariableStats to its own file and redesign it to be extensible.
Moved the IR unit test to the CodeGen folder to resolve linker errors:

error: undefined reference to 'vtable for llvm::DroppedVariableStatsIR'