[CGData] Fix -Wpessimizing-move in CodeGenDataReader.cpp (NFC)
Summary:
/llvm-project/llvm/lib/CodeGenData/CodeGenDataReader.cpp:78:12:
error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
    return std::move(E);
           ^
/llvm-project/llvm/lib/CodeGenData/CodeGenDataReader.cpp:78:12: note: remove std::move call here
    return std::move(E);
           ^~~~~~~~~~ ~
1 error generated.

Test Plan: 

Reviewers: 

Subscribers: 

Tasks: 

Tags: 


Differential Revision: https://phabricator.intern.facebook.com/D60251095