[mlir][cmake] Add missing MLIRTestDialect dependencies
This cherry picks
[mlir][cmake] Add missing MLIRTestDialect dependency (#125004) (72b73c9af694198096b2e0c47a1625e5b94c76a5)
and
[mlir] Fix build race condition in Pass Manager tests (d906da5ead2764579395e5006c517f2ec9afd46f)
to the 20.x release branch.

Both of these are addressing issues that started with
https://github.com/llvm/llvm-project/pull/123910, which is already on the 20.x branch.

In each case the cherry-picked changes correct problems that would otherwise be
a race condition in certain builds. Linaro noticed this on our flang dylib (shared library)
build bot.

Failures look like:
In file included from /home/tcwg-buildbot/worker/flang-aarch64-dylib/llvm-project/mlir/test/lib/Pass/TestPassManager.cpp:10:
/home/tcwg-buildbot/worker/flang-aarch64-dylib/llvm-project/mlir/test/lib/Pass/../Dialect/Test/TestOps.h:148:10: fatal error: 'TestOps.h.inc' file not found
  148 | #include "TestOps.h.inc"
      |          ^~~~~~~~~~~~~~~

We have tested these changes on the buildbot for the last 2 days and had no problems.
Whereas before it was failing maybe 1 in 10 builds, enough that multiple people
in the community noticed it.

Reported in https://github.com/llvm/llvm-project/issues/124485 and
https://github.com/llvm/llvm-project/issues/124335.

Co-authored-by: Diego Caballero <dieg0ca6aller0@gmail.com>